### PR TITLE
Add ling

### PR DESCRIPTION
**Pull request by lanikaling**
I have added myself to people.yml. Please merge. @sbillinge

### CODE REVIEW

**Comment by sbillinge** [comment]
Thanks Lin, great job!

There is something broken with the rg-db-public that needs debugging, as it is failing CI.  This is almost certainly something to do with the html builder.  It is probably not something that you should get started with as it could be tricky, but if you want to try you can....

I can't merge anything until we fix this.  I don't see anything wrong with your entry so it is not your edits that are causing issues.  That said, there is another version of you that my onboarder will have created so we will have trouble merging them both.  We can revisit this when we sort out why it is failing CI.

**Comment by st3107** [comment]
Close and reopen to trigger the CI.

**Comment by st3107** [comment]
Close and reopen to trigger the CI.

**Comment by sbillinge** [comment]
@lanikaling this has a conflict now.   Please work with Daniela on this one too.  

Please rebase and ``push --force-with-lease`` and DO NOT use the "resolve conflicts" to do this.

**Pull request closed without merging**
