### PR TITLE
added Gianluca Paglia

### PR DESCRIPTION
**Pull request by maak-sdu**
Passed locally. Work in progress.

### CODE REVIEW

**Comment by maak-sdu** [comment]
@sbillinge Unfortunately, I have not been able to fine any information for Marek Schmidt (person 13 in the issue) and Mohamed Kemali (person 15).
If you want, I can just add them with their Billinge Group info? Then I just need to know, at which institution(s), they were enrolled?

**Comment by maak-sdu** [comment]
@sbillinge Your welcome.
Thanks for your immediate response! 
Were Marek and Kemali enrolled in your group at Michigan State?

**Comment by sbillinge** [comment]
sorry, yes.  That is the case.

**Comment by sbillinge** [comment]
Thanks so much @maak-sdu great job.  You are graduated from GitHub school! 👍

**Pull request merged**
