### PR TITLE
adding_louis_to_people

### PR DESCRIPTION
**Pull request by OpusXI**

### CODE REVIEW

**Comment by sbillinge** [comment]
Thanks @OpusXI nice work.  If it is not there please could you put in your github id and if you have an ORCID id, that too (you may not).

**Comment by sbillinge** [comment]
@OpusXI did you see my comment?  I would like to merge this if possible.  Thanks so much.

**Comment by OpusXI** [comment]
@sbillinge I'm sorry I missed it. I have updated my Github id. However I do not have at ORCID id.

**Comment by sbillinge** [comment]
thanks @OpusXI .  No worries on the ORCID, that is mostly for grad students.  It is a unique ID for your research work throughout your life....sign up for one if you think you will do published research in the future!

**Pull request merged**
