### PR TITLE
gitid added

### PR DESCRIPTION
**Pull request by akshayc-01**

### CODE REVIEW

**Comment by sbillinge** [comment]
@akshayc-01 this is failing CI

**Comment by sbillinge** [comment]
CI still failing I am afraid.  Please run tests locally till they pass.  If it fails locally it will fail in CI so at least getting it to pass locally is a good first step.

**Comment by st3107** [comment]
Close and reopen to trigger CI.

**Comment by st3107** [comment]
Close and reopen to trigger CI.

**Comment by st3107** [comment]
Haha, I fixed the CI problem. The repo is disabled in the travis CI and I re-enable it. Now the travis CI and the github can talk to each other. And you can see the failure message instead of always running.

Please look at the bug:

`ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
  in "../db/people.yml", line 46, column 3
found duplicate key "github_id" with value "akshayc-01" (original value: "akshayc-01")
  in "../db/people.yml", line 70, column 3`

You have duplicate keys in people at line 46 and line 70.

**Comment by sbillinge** [comment]
@akshayc-01 it looks as if this can be fixed by removing a duplicate github_id key, or sthg like that.

**Comment by sbillinge** [comment]
@akshayc-01 I added these edits manually so I am closing this.

**Pull request closed without merging**
