### PR TITLE
update strumining citation with accepted info

### PR DESCRIPTION
**Pull request by dragonyanglong**
@sbillinge , this is for updating structure-mining paper citation with accepted information and adding acknow.

### CODE REVIEW

**Comment by dragonyanglong** [comment]
Thanks @sbillinge , I updated. It seems like there are some rebase issues here. I did `git fetch upstream master` and `git rebase upstream/master`, then it seems getting quite complex here...

**Comment by sbillinge** [comment]
@dragonyanglong yah, it looks as if you maybe inadvertently merged master into this once or twice.

**Comment by sbillinge** [comment]
I closed this pr and manually added the edits to the strumining paper

**Comment by dragonyanglong** [comment]
I see. Thanks Simon.

**Pull request closed without merging**
