### PR TITLE
DOC: finished Adeolu Ajayi profile on people.yml

### PR DESCRIPTION
**Pull request by aajayi-21**

### CODE REVIEW

**Review by sbillinge — COMMENTED** [review]
Thanks Ade, great job!

This has merge conflicts with the main branch.  It means that something changed since you created the branch and your edits overlap those changes.   This can be fixed with merges, but since you only changed one line, the best is to sync your main, create a new branch, redo the edit (copy-paste) and make a new PR, and then close this one (and delete it from your local for good housekeeping).

We would also put your cunent degree in the education field.  It will be a list with one entry.

**Review by sbillinge — COMMENTED** [review]
please see inline comment, but also this is out of sync with the main branch so can't be merged.  Steps to address this are:
1) on your terminal or in pycharm, in rg-db-public check out main 
2) `git pull upstream main
3) check out the branch again
4) using Pycharm (bottom right hand corner) click on the name of the branch and the little "graph" icon, select main, then select "merge main into <branchname>"
5) then go through the steps, taking everything from main (these are already merged edits so the assumption is that they are good), everything from yours that doesn't have a conflict, and then finding the one or two things from your branch that are conflcts and resolving them.

Actually, in your case, since there is only one line edited, it is way easier to copy that line to the clipboard, make a new branch off a synchronized main, paste in the edit, and create a new PR, and close the old one.

**Comment by sbillinge** [comment]
@aajayi-21 gentle ping on this.  I can't close your rg-db-group PR until this one merges because in that PR you say that you finished this task, but this task is only finished when it merges.

Reach out if you have questions.

**Comment by sbillinge** [comment]
@aajayi-21 gentle ping on this.  Please see my review.  Make sure your notifications are set up so you see these, but I usually respond quickly.

The branch is conflicted.   To fix this, don't close this branch, but....

1.  check out main
2.  sync main with upstream
3.  check out `finishing_my_profle` branch
4.  Using pycharm (recommended) or otherwise, merge `main` into `finishing_my_profile`
5.  push to this PR by pushing to your origin. `git push` should work if you linked your local correctly

I will receive a notification and can check and merge.  For education, just put your undergrad degree (with expected graduation date)

**Review by sbillinge — COMMENTED** [review]
oops, it looks as if you didn't successfully sync your main before doing the merge....so the merge was successful (Well done with that!) but you merged an out of date version of main.  Please can you try again?  Reach out to Dom (or me) if you have a problem.

**Comment by sbillinge** [comment]
@aajayi-21 I'm closing this.  I think it is out of date and there are lots of issues there.  Please can you check your entry in people.yml and make sure it is ok.  Now you are expert in forking workflow it will be a 2 minute job to fix it if anything needs fixing (usually bio and education fields)

**Comment by aajayi-21** [comment]
I will check and update it if there are any issues

**Pull request closed without merging**
