### PR TITLE
ENH: Add Addis Ababa University, Ethiopia

### LINKED ISSUE #61: materials, U. Addis Ababa, Ethiopia

### PR DESCRIPTION
**Pull request by dragonyanglong**
Close #61

### CODE REVIEW

**Comment by sbillinge** [comment]
I am pretty sure that you are not doing the rebase correctly.  It looks as if you merged master onto your branch or something.  I shouldn't be seeing all those commits from other people.  Please can you work with @CJ-Wright and @chiahaoliu  and @sbanerjee23  to sort this out?

Merging/rebasing is hard, but I think we can get there!

**Comment by sbanerjee23** [comment]
We need something in the README that says not to use GitHub's "resolve conflicts" web interface, otherwise everyone will continue to do that.

**Comment by sbanerjee23** [comment]
Rebasing is not hard. Especially when you don't press a magic button to do it and understand what's happening.

**Comment by sbillinge** [comment]
@sbanerjee23 please could you put a PR into the docs with the "don't use "resolve conflicts" button advice?  Thanks.

S

**Comment by sbanerjee23** [comment]
Sure, after you merge or edit the existing rebasing PR I can do that.

**Comment by sbillinge** [comment]
@sbanerjee23 did you see the comments on the rebase PR?  I think there is a way to go before that is pulled in.     You could open a new PR for this one (don't use the button) perhaps?

**Comment by sbanerjee23** [comment]
@sbillinge Okay sounds good Simon.

**Comment by sbillinge** [comment]
@dragonyanglong to avoid problems here I suggest that you copy-paste your edits, then simply wipe out your existing branch and start over for this one.  it will be much less work than cleaning this up.

**Comment by dragonyanglong** [comment]
Thanks @sbillinge, sounds like a good idea. Will do. I guess I accidentally did `git pull` from master branch during the rebase, causing this problem.

**Comment by dragonyanglong** [comment]
Just redo edits in PR #91 .

**Pull request closed without merging**
