### PR TITLE
added Jiwu Liu

### PR DESCRIPTION
**Pull request by berrakozer**
Work in progress.

### CODE REVIEW

**Comment by berrakozer** [comment]
@sbillinge the first test passed and then it started failing. I checked the indentations and everything. What can be the reason so that I can try to fix it again?

**Comment by sbillinge** [comment]
@berrakozer its failing because of duplicate keys.  Actually Emil is already in people because he is currently our colleague at BNL working with Rob.  I think his original entry is pretty up to date so you may be able to just delete him from your list, but please check that his info is as good as it can be and merge in anything that you have that isn't there already

**Comment by sbillinge** [comment]
@berrakozer I'm closing this PR.  The CI is working now so these commits are all passing.  Do you need to add more or should I merge the other Jiwu branch?

**Comment by berrakozer** [comment]
@sbillinge I'm going to add Wenduo Zhou (9/06-06/09, permanent position at ORNL)
and Asel Sartbaeva (2005-2007, Royal Society Research Fellow, Oxford University) but will do another PR.

**Pull request closed without merging**
